/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

const config = require('../lib/config')
const util = require('../lib/util')
const {rebaseOnevnStringFilesOnChromiumL10nFiles, onevnAutoGeneratedPaths} = require('./l10nUtil')

const chromiumRebaseL10n = async (options) => {
  await rebaseOnevnStringFilesOnChromiumL10nFiles()
  onevnAutoGeneratedPaths.forEach((sourceStringPath) => {
    const cmdOptions = config.defaultOptions
    cmdOptions.cwd = config.projects['onevn-core'].dir
    util.run('python', ['script/chromium-rebase-l10n.py', '--source_string_path', sourceStringPath], cmdOptions)
  })
}

module.exports = chromiumRebaseL10n
